version: '2'

services:
    recommender:
        build:
            context: .
        image: kcz17/recommender
        hostname: recommender
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
        ports:
            - "8080:80"
